version: "3.7"
services:
  bot:
    build:
      context: ./
      dockerfile: cmd/bot/Dockerfile
    container_name: bot
    volumes:
      - ./.db:/app/.db
    restart: always

volumes:
  bot-data:
